### ISSUE TITLE
src/match.js -- MatchTurnSubmitRequest body should contain `next_gamer` not `next_gamer_id`

### ISSUE THREAD

**Issue by maxg7** [heroiclabs/heroiclabs-sdk-web#14] opened 2016-11-03 23:43 UTC
According to the documentation regarding [turn submissions](https://heroiclabs.com/docs/concepts/multiplayer/turn-based/#turn-submissions) and the API response when using the websdk, the next_gamer_id body property needs to be next_gamer. When I made the adjustment locally it worked.

```
/**
 * Submit a new turn to the specified match.
 */
export class MatchTurnSubmitRequest extends ApiRequest {

  /**
   * @param  {Session} session Session identifying the account making this request.
   * @param  {String} matchId The match ID to submit.
   * @param  {Integer} lastSeenTurnNumber The last turn number seen by this client for the match.
   * @param  {String} nextGamerId The gamer ID of the gamer who must submit a turn next.
   * @param  {Object} turnData The turn data itself.
   * @return {MatchTurnSubmitRequest} An instance of this object.
   */
  constructor(session, matchId, lastSeenTurnNumber, nextGamerId, turnData) {
    var body = {
      'last_turn': lastSeenTurnNumber,
      **'next_gamer_id': nextGamerId,**
      'data': turnData
    };
    super('POST', '/v0/gamer/match/' + matchId + '/turn', session, body);
  }
}

```

**Comment by mofirouz** [comment] 2016-11-04 09:49
@maxg7 Actually it should contain the `next_gamer_id` as the `next_gamer` is deprecated. Please refer to [this link](https://heroiclabs.com/docs/api/v0/#/v0/match_id_turn_post/) as the spec.

I'll update the concept documentation to carefully reflect this. Thanks again!

**Comment by mofirouz** [comment] 2016-11-04 09:49
@maxg7 You also mentioned that you had to make a change to make it work locally. What was the error you were getting before the change?

**Comment by maxg7** [comment] 2016-11-04 14:49
The error message explicitly states: next_gamer_id not valid.
When I make the proposed change then the api call works.

POST https://api.heroiclabs.com/v0/gamer/match/97c5787a02f24e37a83f1c01fbf78a68/turn 400 (Bad Request)
App.js:37 Uncaught (in promise) Responsebody: **Objectmessage: "'next_gamer_id' not valid"**request: Objectstatus: 400__proto__: Objectmessage: "Bad Request"request: MatchTurnSubmitRequeststatus: 400xhr: XMLHttpRequest__proto__: Objectstep @ App.js:37(anonymous function) @ App.js:37



Here's the full request/response:

> {
>         "startedDateTime": "2016-11-04T14:37:56.751Z",
>         "time": 31.95399999822257,
>         "request": {
>           "method": "POST",
>           "url": "https://api.heroiclabs.com/v0/gamer/match/97c5787a02f24e37a83f1c01fbf78a68/turn",
>           "httpVersion": "HTTP/1.1",
>           "headers": [
>             {
>               "name": "Pragma",
>               "value": "no-cache"
>             },
>             {
>               "name": "Origin",
>               "value": "http://localhost:3000"
>             },
>             {
>               "name": "Accept-Encoding",
>               "value": "gzip, deflate, br"
>             },
>             {
>               "name": "Host",
>               "value": "api.heroiclabs.com"
>             },
>             {
>               "name": "Accept-Language",
>               "value": "en-US,en;q=0.8"
>             },
>             {
>               "name": "User-Agent",
>               "value": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36"
>             },
>             {
>               "name": "Content-Type",
>               "value": "application/json; charset=UTF-8"
>             },
>             {
>               "name": "Accept",
>               "value": "application/json"
>             },
>             {
>               "name": "Cache-Control",
>               "value": "no-cache"
>             },
>             {
>               "name": "Authorization",
>               "value": "Basic -----redacted------"
>             },
>             {
>               "name": "Connection",
>               "value": "keep-alive"
>             },
>             {
>               "name": "Referer",
>               "value": "http://localhost:3000/"
>             },
>             {
>               "name": "Content-Length",
>               "value": "89"
>             },
>             {
>               "name": "DNT",
>               "value": "1"
>             }
>           ],
>           "queryString": [],
>           "cookies": [],
>           "headersSize": 855,
>           "bodySize": 89,
>           "postData": {
>             "mimeType": "application/json; charset=UTF-8",
>             "text": "{\"last_turn\":0,\"next_gamer_id\":\"IrrelevantSister4759\",\"data\":\"{\\\"spoke\\\":7,\\\"ring\\\":10}\"}"
>           }
>         },
>         "response": {
>           "status": 400,
>           "statusText": "Bad Request",
>           "httpVersion": "HTTP/1.1",
>           "headers": [
>             {
>               "name": "date",
>               "value": "Fri, 04 Nov 2016 14:37:56 GMT"
>             },
>             {
>               "name": "content-encoding",
>               "value": "gzip"
>             },
>             {
>               "name": "server",
>               "value": "Apache"
>             },
>             {
>               "name": "content-type",
>               "value": "application/json; charset=utf-8"
>             },
>             {
>               "name": "access-control-allow-origin",
>               "value": "*"
>             },
>             {
>               "name": "access-control-expose-headers",
>               "value": ""
>             },
>             {
>               "name": "cache-control",
>               "value": "max-age=0, private, must-revalidate"
>             },
>             {
>               "name": "access-control-allow-credentials",
>               "value": "true"
>             },
>             {
>               "name": "Connection",
>               "value": "keep-alive"
>             },
>             {
>               "name": "Content-Length",
>               "value": "504"
>             },
>             {
>               "name": "x-request-id",
>               "value": "02gqaag5nstfoclmol5295bsnrkt3fd2"
>             }
>           ],
>           "cookies": [],
>           "content": {
>             "size": 761,
>             "mimeType": "application/json",
>             "compression": 257,
>             "text": "{\"status\":400,\"request\":{\"uri_path\":\"/v0/gamer/match/97c5787a02f24e37a83f1c01fbf78a68/turn\",\"method\":\"POST\",\"headers\":{\"x-forwarded-proto\":\"https\",\"x-forwarded-port\":\"443\",\"x-forwarded-for\":\"108.27.211.241\",\"user-agent\":\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36\",\"referer\":\"http://localhost:3000/\",\"pragma\":\"no-cache\",\"origin\":\"http://localhost:3000\",\"host\":\"api.heroiclabs.com\",\"dnt\":\"1\",\"content-type\":\"application/json; charset=UTF-8\",\"content-length\":\"89\",\"connection\":\"keep-alive\",\"cache-control\":\"no-cache\",\"authorization\":\"[hidden]\",\"accept-language\":\"en-US,en;q=0.8\",\"accept-encoding\":\"gzip, deflate, br\",\"accept\":\"application/json\"}},\"message\":\"'next_gamer_id' not valid\"}"
>           },
>           "redirectURL": "",
>           "headersSize": 402,
>           "bodySize": 504,
>           "_transferSize": 906
>         },
>         "cache": {},
>         "timings": {
>           "blocked": 2.493,
>           "dns": -1,
>           "connect": -1,
>           "send": 0.2400000000000002,
>           "wait": 27.875,
>           "receive": 1.3459999982225703,
>           "ssl": -1
>         },
>         "serverIPAddress": "52.2.202.67",
>         "connection": "178426",
>         "pageref": "page_9"
>       }



Here's a working request/response after the proposed change takes effect:
     

>  {
>         "startedDateTime": "2016-11-04T14:46:16.541Z",
>         "time": 35.85699999530334,
>         "request": {
>           "method": "POST",
>           "url": "https://api.heroiclabs.com/v0/gamer/match/97c5787a02f24e37a83f1c01fbf78a68/turn",
>           "httpVersion": "HTTP/1.1",
>           "headers": [
>             {
>               "name": "Pragma",
>               "value": "no-cache"
>             },
>             {
>               "name": "Origin",
>               "value": "http://localhost:3000"
>             },
>             {
>               "name": "Accept-Encoding",
>               "value": "gzip, deflate, br"
>             },
>             {
>               "name": "Host",
>               "value": "api.heroiclabs.com"
>             },
>             {
>               "name": "Accept-Language",
>               "value": "en-US,en;q=0.8"
>             },
>             {
>               "name": "User-Agent",
>               "value": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36"
>             },
>             {
>               "name": "Content-Type",
>               "value": "application/json; charset=UTF-8"
>             },
>             {
>               "name": "Accept",
>               "value": "application/json"
>             },
>             {
>               "name": "Cache-Control",
>               "value": "no-cache"
>             },
>             {
>               "name": "Authorization",
>               "value": "Basic ---redacted----"
>             },
>             {
>               "name": "Connection",
>               "value": "keep-alive"
>             },
>             {
>               "name": "Referer",
>               "value": "http://localhost:3000/"
>             },
>             {
>               "name": "Content-Length",
>               "value": "85"
>             },
>             {
>               "name": "DNT",
>               "value": "1"
>             }
>           ],
>           "queryString": [],
>           "cookies": [],
>           "headersSize": 855,
>           "bodySize": 85,
>           "postData": {
>             "mimeType": "application/json; charset=UTF-8",
>             "text": "{\"last_turn\":0,\"next_gamer\":\"IrrelevantSister4759\",\"data\":\"{\\\"spoke\\\":4,\\\"ring\\\":3}\"}"
>           }
>         },
>         "response": {
>           "status": 204,
>           "statusText": "No Content",
>           "httpVersion": "HTTP/1.1",
>           "headers": [
>             {
>               "name": "date",
>               "value": "Fri, 04 Nov 2016 14:46:16 GMT"
>             },
>             {
>               "name": "server",
>               "value": "Apache"
>             },
>             {
>               "name": "content-type",
>               "value": "application/json; charset=utf-8"
>             },
>             {
>               "name": "access-control-allow-origin",
>               "value": "*"
>             },
>             {
>               "name": "access-control-expose-headers",
>               "value": ""
>             },
>             {
>               "name": "cache-control",
>               "value": "max-age=0, private, must-revalidate"
>             },
>             {
>               "name": "access-control-allow-credentials",
>               "value": "true"
>             },
>             {
>               "name": "Connection",
>               "value": "keep-alive"
>             },
>             {
>               "name": "content-length",
>               "value": "0"
>             },
>             {
>               "name": "x-request-id",
>               "value": "2q2o9on1cjgbmcknti5n0k28ddngloo5"
>             }
>           ],
>           "cookies": [],
>           "content": {
>             "size": 0,
>             "mimeType": "application/json",
>             "compression": 0
>           },
>           "redirectURL": "",
>           "headersSize": 375,
>           "bodySize": 0,
>           "_transferSize": 375
>         },
>         "cache": {},
>         "timings": {
>           "blocked": 2.807,
>           "dns": -1,
>           "connect": -1,
>           "send": 0.18100000000000005,
>           "wait": 31.852000000000004,
>           "receive": 1.0169999953033368,
>           "ssl": -1
>         },
>         "serverIPAddress": "52.202.246.63",
>         "connection": "179877",
>         "pageref": "page_13"
>       }

**Comment by mofirouz** [comment] 2016-11-04 14:57
@maxg7 The problem is that you are passing nickname as the gamer_id. You'd need to pass the gamerID as the value of this parameter. Please have a look at [this test](https://github.com/heroiclabs/heroiclabs-sdk-web/blob/master/test/sdktest.js#L310) and [this](https://github.com/heroiclabs/heroiclabs-sdk-web/blob/master/test/sdktest.js#L141) for more info.

I'll close this issue as this is not a SDK problem.

**Closed by mofirouz** 2016-11-04 14:57 UTC

**Comment by maxg7** [comment] 2016-11-04 15:19
Gotcha. Then [these docs](https://heroiclabs.com/docs/guide/web/#turn-submission) should be updated since they still call out nextPlayerNickname. The was a discrepancy between the Web Guide and the Api Docs. Seems like either will work as long as the underlying curl request is fine but if we're using the sdk-web then using the gamer_id.

```

// you'll need to keep track of match state in multiplayer games
var lastTurnCount = 2;
var nextPlayerNickname = "abc";
// you should use whatever format best represents your match state changes
var turnData = "e4 e5"; // For example - chess uses portable game notation (PGN)
var request = new Heroic.MatchTurnSubmitRequest(session, match.match_id, lastTurnCount, nextPlayerNickname, turnData);
client.execute(request).then(function (response) {
  console.log("Your turn has been submitted.");
}).catch(errorHandler);
```

**Comment by mofirouz** [comment] 2016-11-04 15:20
Yep you are right. I'll update the docs. 

For what it's worth, the `next_gamer` still works (with a nickname) but it's deprecated in favour of `next_gamer_id` (with a gamer ID) as nicknames can change mid-match.
